// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJRF3604oB9B5i6SdRWzpvrkXUBQLImDc',
    appId: '1:885193792439:web:5008b2f4b499eb62986632',
    messagingSenderId: '885193792439',
    projectId: 'fir-auth-cc85e',
    authDomain: 'fir-auth-cc85e.firebaseapp.com',
    storageBucket: 'fir-auth-cc85e.appspot.com',
    measurementId: 'G-9DJJR3M6YX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm-ZXiJa2GIq47arBO56aUbTJkBgPBEkQ',
    appId: '1:885193792439:android:c921b8dfa8c2288f986632',
    messagingSenderId: '885193792439',
    projectId: 'fir-auth-cc85e',
    storageBucket: 'fir-auth-cc85e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHJIgWG-4NInVkhuYhmDoH2yHE0ItrILg',
    appId: '1:885193792439:ios:18cefb5f77f6f9c2986632',
    messagingSenderId: '885193792439',
    projectId: 'fir-auth-cc85e',
    storageBucket: 'fir-auth-cc85e.appspot.com',
    iosBundleId: 'com.example.userAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHJIgWG-4NInVkhuYhmDoH2yHE0ItrILg',
    appId: '1:885193792439:ios:bbdf1b9b30721fdf986632',
    messagingSenderId: '885193792439',
    projectId: 'fir-auth-cc85e',
    storageBucket: 'fir-auth-cc85e.appspot.com',
    iosBundleId: 'com.example.userAuth.RunnerTests',
  );
}
